# @package actions
train_model:
   _target_: src.actions.train.train_model
   data_dir: ${paths.data_dir}
   data_fn: ${dataset_output_fn}
   target_variable: ${dataset.target_variable}
   predictor: ${model.predictor}
   model_tag: ${model.tag}
   input_scaler: ${input_scaler}
   output_scaler: ${output_scaler}
   tag: ${model.tag}
   test_size: ${dataset.test_size}
   random_state: ${seed}