# @package actions
train_model:
   _target_: src.actions.train_val.train_val
   data_dir: ${paths.data_dir}
   data_fn: ${dataset_output_fn}
   log_dir: ${paths.log_dir}
   target_variable: ${dataset.target_variable}
   model_pipeline: ${model.pipeline}
   model_tag: ${model.tag}
   metrics: ${metrics}
   test_size: ${dataset.test_size}
   random_state: ${seed}
