PLOTLY_LAYOUT_CFG = {
    "font": {"family": "Arial, sans-serif", "size": 14, "color": "#333333"},
    "title": {"x": 0.5, "xanchor": "center", "font": {"size": 18, "color": "#222222"}},
    "width": 800,
    "height": 600,
    "margin": {"l": 50, "r": 50, "t": 50, "b": 50},
    "xaxis": {
        "title": {"font": {"size": 14}},
        "showgrid": True,
        "gridcolor": "#e6e6e6",
        "zeroline": False,
        "linecolor": "#cccccc",
        "mirror": True,
    },
    "yaxis": {
        "title": {"font": {"size": 14}},
        "showgrid": True,
        "gridcolor": "#e6e6e6",
        "zeroline": False,
        "linecolor": "#cccccc",
        "mirror": True,
    },
    "legend": {"font": {"size": 12}, "bordercolor": "#cccccc", "borderwidth": 1},
    "paper_bgcolor": "#ffffff",
    "plot_bgcolor": "#f9f9f9",
    "colorway": [
        "#636EFA",
        "#EF553B",
        "#00CC96",
        "#AB63FA",
        "#FFA15A",
        "#19D3F3",
        "#FF6692",
        "#B6E880",
        "#FF97FF",
        "#FECB52",
    ],
}
